### ISSUE TITLE
这个登录使用场景是什么呢？打算实现的功能是什么

### ISSUE THREAD

**Issue by liuzj288** [mengxinyuan638/nonebot-plugin-bilibili-yuan#1]

**Comment by mengxinyuan638** [comment]
我打算扫码登录获取cookie，然后能展示个人信息，用bv号提取视频链接，然后可以在q群投币某个视频，或者发送bv号能自动搜索到对应视频链接，并发送给用户，还有能够搜索视频，up，并且返回详情信息，现在就想到这些，其实本来写这个插件是想要锻炼我异步爬虫相关的技术能力的，后来发现还可以拓展更多新功能，不过得等后续拓展了，或者有大佬能帮忙完善

**Comment by mengxinyuan638** [comment]
这边先关闭issue了
