### ISSUE TITLE
您还有正在使用的二维码，请等待二维码失效后重新申请

### ISSUE THREAD

**Issue by Annnnh1010** [mengxinyuan638/nonebot-plugin-bilibili-yuan#2]

**Comment by mengxinyuan638** [comment]
等待二维码失效后再尝试申请，一般5分钟就好了

**Comment by Annnnh1010** [comment]
但是一直是这样的提示 不管过了多久 重启也这样

**Comment by mengxinyuan638** [comment]
尝试删除一下bot根目录下的bilibili_login目录或者删除bilibili_login目录内对应qq号txt文件，一般来说这样提示就是你申请过二维码，还没失效，等待机器人提示二维码已失效重新申请即可
